
const temas = [
    { tema:01, estado: 'excelente', numero:0 , nombre:'Fundamentación psicológica y pedagógica del currículo. Aportaciones de la Psicología y Ciencias de la Educación al diseño curricular en sus distintos niveles.'},
    { tema:02, estado: 'satisfactorio', numero:0 , nombre:'Las capacidades como objetivo de la educación. Sus distintos aspectos: valor intrínseco, valor propedéutico, carácter funcional en relación con la vida cotidiana.'},
    { tema:03, estado: 'mejorable', numero:0 , nombre:'Procesos de aprendizaje: condicionamiento, aprendizaje por observación, aprendizajes superiores, el procesamiento de la información, el papel de la atención y la memoria, las habilidades metacognitivas.'},
    { tema:04, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:05, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:06, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:07, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:08, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:09, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:10, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:11, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:12, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:13, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:14, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:15, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:16, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:17, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:18, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:19, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:20, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:21, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:22, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:23, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:24, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:25, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:26, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:27, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:28, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:29, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:30, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:40, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:41, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:42, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:43, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:44, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:45, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:46, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:47, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:48, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:49, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:50, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:51, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:52, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:53, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:54, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:55, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:56, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:57, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:58, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:59, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:60, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:61, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:62, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:63, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:64, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:65, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:66, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:67, estado: 'insuficiente', numero:0 , nombre:''},
    { tema:68, estado: 'insuficiente', numero:0 , nombre:''}
  ]


  