
const temas = [
    { tema:01, estado: 'excelente', numero:1 , nombre:'Fundamentación psicológica y pedagógica del currículo. Aportaciones de la Psicología y Ciencias de la Educación al diseño curricular en sus distintos niveles.'},
    { tema:02, estado: 'insuficiente', numero:0 , nombre:'Las capacidades como objetivo de la educación. Sus distintos aspectos: valor intrínseco, valor propedéutico, carácter funcional en relación con la vida cotidiana.'},
    { tema:03, estado: 'satisfactorio', numero:2 , nombre:'Procesos de aprendizaje: condicionamiento, aprendizaje por observación, aprendizajes superiores, el procesamiento de la información, el papel de la atención y la memoria, las habilidades metacognitivas.'},
    { tema:04, estado: 'excelente', numero:0 , nombre:'El proceso de enseñanza y aprendizaje como proceso de construcción y de interacción: elementos interpersonales y elementos didácticos. El papel mediador del profesor.'},
    { tema:05, estado: 'insuficiente', numero:0 , nombre:'Principios didácticos en el proceso de enseñanza y aprendizaje. Aprendizaje significativo. El papel de las capacidades y conocimientos previos. La personalización de los procesos de enseñanza-aprendizaje.'},
    { tema:06, estado: 'excelente', numero:0 , nombre:'El desarrollo en la edad de la Educación Infantil (I): desarrollo social, motor y afectivo. Implicaciones educativas.'},
    { tema:07, estado: 'satisfactorio', numero:0 , nombre:'El desarrollo en la edad de la Educación Infantil (II): lenguaje y comunicación; el pensamiento percepto-motor. Implicaciones educativas.'},
    { tema:08, estado: 'satisfactorio', numero:0 , nombre:'El desarrollo en la edad de la Educación Primaria (I): desarrollo social, motor y afectivo. Implicaciones educativas.'},
    { tema:09, estado: 'satisfactorio', numero:0 , nombre:'El desarrollo en la edad de la Educación Primaria (II): lenguaje y comunicación; el pensamiento concreto. Implicaciones educativas.'},
    { tema:10, estado: 'satisfactorio', numero:0 , nombre:'El desarrollo en la edad de la Educación Secundaria (I): Adolescencia y juventud. Cambios que acompañan a la pubertad. Implicaciones educativas.'},
    { tema:11, estado: 'satisfactorio', numero:0 , nombre:'El desarrollo en la edad de la Educación Secundaria (II): desarrollo cognitivo; el pensamiento formal abstracto. Implicaciones educativas.'},
    { tema:12, estado: 'insuficiente', numero:0 , nombre:'Socialización y aprendizaje. La escuela como institución socializadora: la transmisión en ella de pautas sociales y valores. Tradición y patrimonio cultural en la transmisión educativa.'},
    { tema:13, estado: 'insuficiente', numero:0 , nombre:'La dimensión moral en la educación. Actitudes y valores morales a través de las áreas del currículo. La educación del razonamiento y del juicio moral.'},
    { tema:14, estado: 'insuficiente', numero:0 , nombre:'Educación para la convivencia y para la paz. La educación y el desarrollo de actitudes cooperativas, democráticas y cívicas.'},
    { tema:15, estado: 'insuficiente', numero:0 , nombre:'Educación para la igualdad. Educación no discriminatoria. Eliminación de prejuicios sexistas y racistas en la escuela.'},
    { tema:16, estado: 'insuficiente', numero:0 , nombre:'Educación sexual y educación para la salud. Prevención de las drogodependencias.'},
    { tema:17, estado: 'insuficiente', numero:0 , nombre:'La tutoría como elemento de la función docente. Funciones del tutor en Primaria y en Secundaria. Aportaciones de la Psicología y de las Ciencias de la Educación al desarrollo de estas funciones.'},
    { tema:18, estado: 'insuficiente', numero:0 , nombre:'El proceso de tomar decisiones: cómo se aprende y cómo se enseña.'},
    { tema:19, estado: 'insuficiente', numero:0 , nombre:'La madurez vocacional y el proyecto de vida. Aportación de la Psicología y la Pedagogía a esta madurez y proyecto, principalmente en la adolescencia.'},
    { tema:20, estado: 'insuficiente', numero:0 , nombre:'Aspectos de la diversidad de condiciones personales de los alumnos relevantes para la educación y el aprendizaje: aptitudes, motivación, estilos cognitivos, otras diferencias individuales.'},
    { tema:21, estado: 'insuficiente', numero:0 , nombre:'La orientación como actividad educativa. Principios básicos comunes a los distintos modelos de orientación educativa. Sus técnicas más utilizadas.'},
    { tema:22, estado: 'insuficiente', numero:0 , nombre:'Presentación y desarrollo de un modelo concreto de orientación educativa, así como de sus instrumentos y técnicas de orientación.'},
    { tema:23, estado: 'insuficiente', numero:0 , nombre:'La organización del sistema de orientación y apoyo en España en las distintas Administraciones educativas.'},
    { tema:24, estado: 'insuficiente', numero:0 , nombre:'Función asesora. Modelo de Intervención.'},
    { tema:25, estado: 'insuficiente', numero:0 , nombre:'La orientación en Educación Secundaria. Modelo de intervención y funciones.'},
    { tema:26, estado: 'insuficiente', numero:0 , nombre:'El asesoramiento individualizado a los alumnos: principios generales, modelos y técnicas.'},
    { tema:27, estado: 'insuficiente', numero:0 , nombre:'Asesoramiento sobre itinerarios educativos acordes con las aptitudes y motivación de los alumnos en la Educación Secundaria: optatividad. Modalidades de Bachillerato, ciclos de Formación Profesional.'},
    { tema:28, estado: 'insuficiente', numero:0 , nombre:'La orientación profesional y los procesos de toma de decisión vocacional. Madurez vocacional, autoconocimiento y elección de estudios y profesiones.'},
    { tema:29, estado: 'insuficiente', numero:0 , nombre:'Entrenamiento en la transición a la vida activa. Asesoramiento sobre estudios superiores en campos profesionales acordes con las aptitudes, intereses y motivación de los alumnos.'},
    { tema:30, estado: 'insuficiente', numero:0 , nombre:'Enseñanza de habilidades básicas y hábitos de autonomía principalmente con alumnos con déficits o disfunciones.'},
    { tema:31, estado: 'insuficiente', numero:0 , nombre:'Programas de enseñanza a pensar, de aprender a aprender: principios comunes y panorama general.'},
    { tema:32, estado: 'insuficiente', numero:0 , nombre:'Presentación y desarrollo de algún programa concreto de intervención para aprender a pensar.'},
    { tema:33, estado: 'insuficiente', numero:0 , nombre:'Métodos y técnicas de trabajo intelectual y su desarrollo en Primaria y en secundaria: principios generales y aplicación en áreas o ámbitos específicos.'},
    { tema:34, estado: 'insuficiente', numero:0 , nombre:'El enfoque preventivo de los problemas escolares y de aprendizaje. Grupos de riesgo y recursos compensatorios.'},
    { tema:35, estado: 'insuficiente', numero:0 , nombre:'Análisis sistémico de la institución escolar. La escuela como sistema de interacciones. El enfoque sistémico en la intervención psicopedagógica: programas de intervención global.'},
    { tema:36, estado: 'insuficiente', numero:0 , nombre:'Relación de teoría y práctica en la educación. La investigación educativa . El profesor como investigador de su propia práctica. Principios y métodos de la investigación en la acción.'},
    { tema:37, estado: 'insuficiente', numero:0 , nombre:'La práctica educativa como relación personal y como práctica técnica y científica. La persona del educador, la tecnología educativa y los medios didácticos.'},
    { tema:38, estado: 'insuficiente', numero:0 , nombre:'Principios y modelos generales de evaluación en educación. Sus fines y sus tipos. La evaluación en el proceso educativo y en la toma de decisiones curriculares.'},
    { tema:39, estado: 'insuficiente', numero:0 , nombre:'Evaluación psicopedagógica: evaluación de la capacidad intelectual, de las aptitudes básicas y de otras características personales relacionadas con el aprendizaje. Instrumentos y técnicas de esta evaluación.'},
    { tema:40, estado: 'insuficiente', numero:0 , nombre:'Evaluación del proceso de enseñanza: evaluación de los proyectos curriculares, de la programación, de los materiales curriculares, de las actividades educativas, de la organización escolar.'},
    { tema:41, estado: 'insuficiente', numero:0 , nombre:'Evaluación del aprendizaje: evaluación de los procesos y de los resultados de aprendizaje en los alumnos. Evaluación de la competencia curricular.'},
    { tema:42, estado: 'insuficiente', numero:0 , nombre:'Experimentación e innovación educativa. Problemas y estrategias en la introducción y difusión de innovaciones educativas en la escuela.'},
    { tema:43, estado: 'insuficiente', numero:0 , nombre:'Dinámica del grupo clase. La adaptación al medio escolar. Negociación de roles en el aula.'},
    { tema:44, estado: 'insuficiente', numero:0 , nombre:'La construcción de la inteligencia y de la personalidad en la interacción social: el papel de los compañeros en la experiencia educativa y en el aprendizaje.'},
    { tema:45, estado: 'insuficiente', numero:0 , nombre:'El trabajo cooperativo y la interacción social. Técnicas de análisis y dinamización grupal.'},
    { tema:46, estado: 'satisfactorio', numero:2 , nombre:'La educación especial: del modelo del déficit al de necesidades educativas especiales. Principios generales de la intervención educativa en estas necesidades.'},
    { tema:47, estado: 'satisfactorio', numero:2 , nombre:'La organización de la educación especial: aulas y centros específicos; integración de alumnos con necesidades educativas especiales en la escuela ordinaria. Principios y métodos de la integración escolar. Criterios de escolarización.'},
    { tema:48, estado: 'insuficiente', numero:0 , nombre:'Organización y modos de trabajo en el aula con alumnos con necesidades especiales. Actuaciones específicas con estos alumnos.'},
    { tema:49, estado: 'satisfactorio', numero:2 , nombre:'Adaptaciones curriculares: conceptos y principios generales. Adaptaciones curriculares significativas para alumnos con necesidades educativas especiales y sus clases: acceso al currículo; adaptaciones metodológicas, en contenidos, en evaluación.'},
    { tema:50, estado: 'satisfactorio', numero:0 , nombre:'La diversificación curricular: aplicaciones de los artículos 23 y 37 de la L.O.G.S.E. Objetivos, áreas, contenidos y criterios para adaptar el currículo a estos alumnos.'},
    { tema:51, estado: 'satisfactorio', numero:2 , nombre:'Las personas con retraso mental: características de su desarrollo. Principios generales de intervención educativa y criterios para adaptar el currículo a estos alumnos.'},
    { tema:52, estado: 'satisfactorio', numero:2 , nombre:'Déficits sensoriales: sus tipos y evaluación. Sistemas de comunicación en alumnos ciegos y sordos.'},
    { tema:53, estado: 'satisfactorio', numero:2 , nombre:'Intervención educativa y adaptaciones curriculares con alumnos ciegos y ambliopes.'},
    { tema:54, estado: 'satisfactorio', numero:2 , nombre:'Intervención educativa y adaptaciones curriculares con alumnos sordos.'},
    { tema:55, estado: 'insuficiente', numero:0 , nombre:'El autismo y las alteraciones de la comunicación en la infancia y la adolescencia. Intervención educativa ante estos problemas.'},
    { tema:56, estado: 'insuficiente', numero:0 , nombre:'Alteraciones comportamentales y conductas asociales en la infancia. Programas de prevención, intervención y tratamiento ante problemas de desarrollo de la personalidad en la Educación Infantil y Primaria.'},
    { tema:57, estado: 'insuficiente', numero:0 , nombre:'Alteraciones comportamentales y conductas asociales en la adolescencia. Programas de prevención, intervención y tratamiento ante problemas de desarrollo de la personalidad en la Educación Secundaria.'},
    { tema:58, estado: 'insuficiente', numero:0 , nombre:'Los alumnos con disfunciones o déficits motores. Barreras de acceso al currículo. Criterios para la adaptación curricular. Sistemas de comunicación alternativa.'},
    { tema:59, estado: 'insuficiente', numero:0 , nombre:'Diferentes ritmos de aprendizaje: Alumnos lentos en aprender. Intervención educativa.'},
    { tema:60, estado: 'insuficiente', numero:0 , nombre:'Dificultades y problemas en la adquisición del lenguaje hablado: intervención educativa.'},
    { tema:61, estado: 'insuficiente', numero:0 , nombre:'Dificultades y problemas en la adquisición del lenguaje escrito: intervención educativa.'},
    { tema:62, estado: 'insuficiente', numero:0 , nombre:'Dificultades y problemas en los aspectos matemáticos básicos y en las operaciones elementales de cálculo: intervención educativa.'},
    { tema:63, estado: 'insuficiente', numero:0 , nombre:'Dificultades y problemas en la adquisición y uso de los instrumentos lógicos y matemáticos del pensamiento formal abstracto en la adolescencia: intervención educativa.'},
    { tema:64, estado: 'insuficiente', numero:0 , nombre:'Los alumnos superdotados. Posibilidades educativas que les ofrece el currículo en las distintas etapas. El trabajo educativo con estos alumnos.'},
    { tema:65, estado: 'insuficiente', numero:0 , nombre:'Formación profesional y preparación para la transición a la vida activa en alumnos que no alcanzan los objetivos de la enseñanza obligatoria. Programas de Garantía Social.'},
    { tema:66, estado: 'insuficiente', numero:0 , nombre:'El papel de la familia en la educación. Colaboración de profesores y padres en las distintas etapas educativas, principalmente en Educación Infantil. Modos de trabajo con los padres.'},
    { tema:67, estado: 'insuficiente', numero:0 , nombre:'La colaboración de maestros y padres de alumnos con necesidades educativas especiales. Programas educativos formales para desarrollar en el hogar.'},
    { tema:68, estado: 'insuficiente', numero:0 , nombre:'La escuela en su entorno: relación con otras instituciones sociales, con la ciudad. Peculiaridades de la escuela rural.'}
  ]
  
  
  

  
